experiment:
  seed: 28
  num_epochs: 200

modalities:
  skeleton:
    model:
      cooccurrence:
        class_name: SupervisedSkeletonCooccurenceModel
        from_module: skeleton_coocurrence
        args: [] # These will be passed as positional args to the LightningModule class.
        kwargs: # These will be passed as kwargs to the LightningModule class.
          batch_size: 64
          out_channels: [64, 32, 32, 64, 128, 256]
          kernel_sizes: [[1, 1], [3, 1], [3, 3], [3, 3], [3, 3], [3, 3]]
          max_pool_sizes: [null, null, [2, 1], [2, 1], [2, 1], [2, 1]]
          sample_length: 50
          lr: 0.001
          optimizer_name: adam
          metric_name: accuracy
    transforms:
      - class_name: VariableLengthRandomCrop
        from_module: skeleton_transforms
        in_test: false
        kwargs:
          crop_p: 0.7
      - class_name: SkeletonSampler
        from_module: skeleton_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 50
      - class_name: ToTensor
        from_module: general_transforms
        in_test: true
      - class_name: Jittering
        from_module: inertial_augmentations
        in_test: false
        kwargs:
          sigma: 0.01
      - class_name: Permute
        from_module: general_transforms
        in_test: true
        kwargs:
          shape: [1, 2, 0]
      - class_name: ToFloat
        from_module: general_transforms
        in_test: true
